backend: tensorflow

dataset:
  schema: cms
  target_particles: cand
  num_input_features: 15
  num_output_features: 7
#       NONE = 0,
#       TRACK = 1,
#       PS1 = 2,
#       PS2 = 3,
#       ECAL = 4,
#       HCAL = 5,
#       GSF = 6,
#       BREM = 7,
#       HFEM = 8,
#       HFHAD = 9,
#       SC = 10,
#       HO = 11,
  num_input_classes: 12
  #(none=0, ch.had=1, n.had=2, hfem=3, hfhad=4, gamma=5, e=6, mu=7)
  num_output_classes: 8
  padded_num_elem_size: 256
  #(pt, eta, sin phi, cos phi, E)
  num_momentum_outputs: 5
  classification_loss_coef: 10000.0
  momentum_loss_coef: 0.0
  charge_loss_coef: 0.0
  momentum_loss_coefs:
    - 1.0
    - 10.0
    - 100.0
    - 100.0
    - 1.0
  raw_path: data/TTbar_14TeV_TuneCUETP8M1_cfi/raw/*.pkl
  processed_path: data/gun/tfr_cand/*.tfrecords
  num_files_per_chunk: 1
  validation_file_path: data/TTbar_14TeV_TuneCUETP8M1_cfi/val/*.pkl

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-5
  batch_size: 100
  num_events_train: 250000
  num_events_test: 50000
  num_epochs: 100
  dtype: float32
  sample_weights: inverse_sqrt
  trainable: all
  multi_output: yes

parameters:
  model: transformer
  num_layers: 2
  d_model: 256
  num_heads: 2
  dff: 256
  support: 32
  skip_connection: yes
  dropout: 0.0

timing:
  num_ev: 100
  num_iter: 3
