backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  num_input_classes: 3
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  momentum_loss_coef: 1.0
  charge_loss_coef: 1.0
  pt_loss_coef: 1.0
  eta_loss_coef: 1.0
  sin_phi_loss_coef: 1.0
  cos_phi_loss_coef: 1.0
  energy_loss_coef: 0.001
  raw_path: data/pythia8_ttbar/*.pkl.bz2
  processed_path: data/pythia8_ttbar/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: data/pythia8_ttbar/val/*.pkl.bz2

tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-6
  batch_size: 5
  num_events_train: 50
  num_events_test: 50
  num_epochs: 1
  dtype: float32
  sample_weights: none
  trainable: all
 
parameters:
  model: gnn
  bin_size: 128
  num_convs_id: 2
  num_convs_reg: 2
  num_hidden_id_enc: 2
  num_hidden_id_dec: 0
  num_hidden_reg_enc: 2
  num_hidden_reg_dec: 0
  num_neighbors: 16 
  hidden_dim_id: 256
  hidden_dim_reg: 256
  distance_dim: 256
  dropout: 0.0
  dist_mult: 1.0
  activation: elu
  skip_connection: True

timing:
  num_ev: 1
  num_iter: 1
