name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  delphes-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install tensorflow==2.4 setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 keras-tuner networkx tensorflow-probability tensorflow-addons
      - name: Run delphes TF model
        run: ./scripts/local_test_delphes_tf.sh

  cms-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install tensorflow==2.4 setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 keras-tuner networkx tensorflow-probability tensorflow-addons
      - name: Run CMS TF model
        run: ./scripts/local_test_cms_tf.sh
  
  delphes-pytorch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 networkx
          sudo python3 -m pip install torch==1.6.0 torchvision==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
          sudo python3 -m pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
          sudo python3 -m pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
          sudo python3 -m pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
          sudo python3 -m pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
          sudo python3 -m pip install torch-geometric comet_ml
      - name: Run Delphes Pytorch model
        run: ./scripts/local_test_delphes_pytorch.sh
